### ISSUE TITLE
Change link color

### ISSUE THREAD

**Issue by MyNameIsJohnson** [jchoomalu/Portfolio#11]
# Summary 

Currently the links default to blue color on hover. 

![image](https://github.com/jchoomalu/Jason-Hoomalu-Portfolio/assets/38548029/0029c91c-dc04-4cf9-bc91-f2b747983aba)

## Solution: 

Change all link color on hover to increase in font weight instead.

**Comment by jchoomalu** [comment]
Completed link update changed link color and style to match overall theme
![Screenshot 2023-12-06 at 4 23 36 AM](https://github.com/jchoomalu/Jason-Hoomalu-Portfolio/assets/149881009/43a967a3-7e3b-435f-9854-1b0eafbc2239)
![Screenshot 2023-12-06 at 4 39 24 AM](https://github.com/jchoomalu/Jason-Hoomalu-Portfolio/assets/149881009/2d334b0c-97f1-48f9-b071-31ebc7403a7c)
