### ISSUE TITLE
Build Nav Component

### ISSUE THREAD

**Issue by MyNameIsJohnson** [jchoomalu/Portfolio#2]
# Nav

Start building your navigation component that includes About, Skills, Projects, Testimonials and Contact.

You could try to integrate [React Bootstrap Nav](https://react-bootstrap.netlify.app/docs/components/navbar/) or explore other libraries like [Material UI](https://mui.com/material-ui/getting-started/)  

Remember to create a new branch, commit your work and push.

If you have this done by Thursday, I'll walk you through creating the pull-request process. 

Happy coding!

**Comment by jchoomalu** [comment]
It’s done already!  But I will keep working on it until you have time to
teach me how to do the pull request.

I used React Bootstrap and even created a logo to showcase my design skills.
