### ISSUE TITLE
Add the About content 

### ISSUE THREAD

**Issue by jchoomalu** [jchoomalu/Portfolio#4]
Add about content and ensure responsiveness using bootstrap

**Comment by MyNameIsJohnson** [comment]
What content would be most important for sprint?

**Comment by jchoomalu** [comment]
> What content would be most important for sprint?

- dedicated to continuing education
- love logic and solving complex problems
- I want to create simple user friendly UX/UI components that simplify daily life

**Comment by jchoomalu** [comment]
config of about section complete moving to Netlify form and resume button
